-- TaskFlow DDL (PostgreSQL / H2 compatible)
-- Автор: Герасименко Константин, 2026

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       VARCHAR(500) NOT NULL,
    description TEXT,
    category    VARCHAR(100) NOT NULL DEFAULT 'Работа',
    priority    VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status      VARCHAR(20) NOT NULL DEFAULT 'TODO',
    due_date    DATE NOT NULL,
    starred     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX idx_tasks_user_id ON tasks(user_id);
CREATE INDEX idx_tasks_due_date ON tasks(due_date);
CREATE INDEX idx_tasks_status ON tasks(status);
